-- Step 1: Deactivate old questions for student 98825c00-fb8f-46dc-bec7-3cdd8880efea
UPDATE quiz_questions
SET active = false
WHERE student_id = '98825c00-fb8f-46dc-bec7-3cdd8880efea'
  AND active = true;

-- Step 2: Insert new 30 questions
INSERT INTO quiz_questions
  (student_id, question_text, question_type, options, correct_answer, concept_tested, difficulty, explanation, active, created_date)
VALUES
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', 'Based on the teacher''s list, which of these requires the article ''the''?', 'mcq', '["An abstract noun like ''love''","The name of a historical event","A regular noun mentioned for the first time","The name of a single mountain"]'::jsonb, 'The name of a historical event', 'Article Usage', 'medium', 'The teacher''s list of uses for ''the'' included historical events. The teacher specifically corrected Anaya about not using ''the'' with abstract nouns.', true, CURRENT_DATE),
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', 'Which sentence means you will arrange for someone else to repair the AC?', 'mcq', '["I will repair the AC by myself.","I get the AC repaired.","I will get the AC repaired.","I had the AC repaired."]'::jsonb, 'I will get the AC repaired.', 'Causative Form', 'medium', 'The structure ''get + object + past participle'' is the causative form, used to show you are causing someone else to perform the action.', true, CURRENT_DATE),
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', 'Which word was spelled correctly during the homework review?', 'mcq', '["Christmes","Rupeese","Thier","Christmas"]'::jsonb, 'Christmas', 'Spelling Corrections', 'easy', 'The teacher corrected the spelling of ''Christmas'' (Christ-mas), ''rupees'' (no ''e'' at the end), and the use of ''there'' vs. ''their''.', true, CURRENT_DATE),
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', 'The sentence ''If I were the Prime Minister...'' is used to talk about...', 'mcq', '["a real future plan.","a past memory.","a hypothetical or imaginary situation.","a direct order."]'::jsonb, 'a hypothetical or imaginary situation.', 'Conditional Sentences (Type 2)', 'hard', 'This ''If I were...'' structure is a key example of the second conditional, used for unreal situations, as discussed in the lesson.', true, CURRENT_DATE),
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', 'What does ''He need not play'' mean?', 'mcq', '["He is unable to play.","He is forbidden from playing.","It is not necessary for him to play.","He must not play."]'::jsonb, 'It is not necessary for him to play.', 'Modal Verbs (Need not)', 'medium', 'As taught in class, ''need not'' is a modal verb that expresses a lack of necessity or obligation.', true, CURRENT_DATE),
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', 'Which of these means ''मैं खेलती थी''?', 'mcq', '["I kept on playing.","I used to play.","I did play.","I had played."]'::jsonb, 'I used to play.', 'Past Habits (Used to)', 'easy', 'The phrase ''used to'' is specifically for describing a habit or state in the past that is no longer true.', true, CURRENT_DATE),
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', 'For a strong obligation like attending an assembly, which modal did the teacher use?', 'mcq', '["should","may","can","must"]'::jsonb, 'must', 'Modal Verbs (Must)', 'medium', 'The teacher used ''You must attend the assembly'' to indicate a strong, non-negotiable obligation.', true, CURRENT_DATE),
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', 'Which preposition is correct for a specific date like the 25th of December?', 'mcq', '["at","in","for","on"]'::jsonb, 'on', 'Prepositions of Time (On)', 'easy', 'The teacher explicitly corrected the student, stating that ''on'' is the correct preposition to use with specific dates.', true, CURRENT_DATE),
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', 'Choose the correct question for the answer ''I am playing.''', 'mcq', '["Did you play?","Do you play?","Are you playing?","Have you played?"]'::jsonb, 'Are you playing?', 'Present Continuous Tense', 'easy', 'The answer is in the present continuous tense, so the question must match that tense structure.', true, CURRENT_DATE),
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', 'The sentence ''I did not play'' is the correct negative form of ''I played''.', 'true_false', '["True","False"]'::jsonb, 'True', 'Simple Past Tense (Negative)', 'easy', 'As practiced in class, the negative past simple uses ''did not'' followed by the base form of the verb (''play'').', true, CURRENT_DATE),
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', 'According to the teacher, ''the'' should be used before abstract nouns like ''love''.', 'true_false', '["True","False"]'::jsonb, 'False', 'Article Usage', 'easy', 'The teacher specifically corrected Anaya, stating that ''the'' is not used with abstract nouns like ''love'' or ''fear''.', true, CURRENT_DATE),
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', 'The sentence ''The shopkeeper had closed the shop'' is in the passive voice.', 'true_false', '["True","False"]'::jsonb, 'False', 'Active and Passive Voice', 'medium', 'This is active voice because the subject (''shopkeeper'') performs the action. The passive version is ''The shop had been closed''.', true, CURRENT_DATE),
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', '''I had to go'' means that it was necessary for me to go in the past.', 'true_false', '["True","False"]'::jsonb, 'True', 'Modal Verbs (Had to)', 'easy', '''Had to'' is the past tense of ''have to'' and expresses a past necessity or obligation.', true, CURRENT_DATE),
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', 'The teacher said the article ''the'' is used before ordinal numbers like ''first''.', 'true_false', '["True","False"]'::jsonb, 'True', 'Article Usage', 'easy', 'When listing the uses for ''the'', the teacher explicitly mentioned ''ordinal numbers'' as one of the rules.', true, CURRENT_DATE),
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', 'How do you tell Anaya ''ghar na jaae''?', 'short_answer', NULL, 'Tell Anaya not to go home.', 'Imperative Negatives', 'medium', 'This requires using the negative imperative structure ''...not to + verb'' which was specifically practiced in the transcript.', true, CURRENT_DATE),
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', 'Why use passive voice for ''the shop''?', 'short_answer', NULL, 'The shop is an object; it cannot close itself.', 'Passive Voice', 'hard', 'The key concept is that the subject of the sentence (the shop) is receiving the action, not performing it.', true, CURRENT_DATE),
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', 'When is ''the'' used with comparative adjectives?', 'short_answer', NULL, 'When there is a sense of selection.', 'Article Usage with Comparatives', 'hard', 'The teacher explained this specific rule: ''He is the better singer between you two,'' implying selection.', true, CURRENT_DATE),
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', 'What does ''I could have played'' imply?', 'short_answer', NULL, 'A missed opportunity to play in the past.', 'Modal Verbs (Could have)', 'hard', 'This structure (''could have'' + past participle) is used for past possibilities that did not happen.', true, CURRENT_DATE),
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', 'What is the error in ''I did not went''?', 'short_answer', NULL, 'After ''did not'', the base verb form is used.', 'Simple Past Tense (Negative)', 'medium', 'The rule is that the auxiliary verb ''did'' carries the past tense, so the main verb returns to its base form (''go'').', true, CURRENT_DATE),
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', 'What word means to say something in an exaggerated way?', 'short_answer', NULL, 'Exaggerating.', 'Vocabulary', 'easy', 'The teacher introduced this word in the question ''Are you exaggerating?''', true, CURRENT_DATE),
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', 'I am going ___ the road.', 'fill_blank', NULL, 'across', 'Prepositions of Movement', 'easy', '''Across'' is the correct preposition to describe movement from one side of an area to the other.', true, CURRENT_DATE),
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', 'He ___ on playing.', 'fill_blank', NULL, 'kept', 'Phrasal Verbs (Keep on)', 'easy', 'The phrase ''kept on'' is the past tense form of ''keep on'', which means to continue doing something.', true, CURRENT_DATE),
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', '___ I come? (Asking if it''s necessary)', 'fill_blank', NULL, 'Need', 'Modal Verbs (Need)', 'medium', 'The structure ''Need I come?'' was taught as the correct interrogative form to ask about necessity.', true, CURRENT_DATE),
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', 'If I ___ the Prime Minister, I would change the rules.', 'fill_blank', NULL, 'were', 'Conditional Sentences (Type 2)', 'medium', 'For hypothetical ''if'' clauses, ''were'' is used for the first and third person singular instead of ''was''.', true, CURRENT_DATE),
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', 'Anaya had been doing garba ___ two months.', 'fill_blank', NULL, 'for', 'Prepositions of Time (For/Since)', 'easy', '''For'' is used for a duration of time (two months), while ''since'' is for a specific starting point.', true, CURRENT_DATE),
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', 'I ___ play. (Emphasizing that you do play)', 'fill_blank', NULL, 'do', 'Emphatic Tense', 'easy', 'Using ''do'' before the verb in an affirmative sentence adds emphasis, as in ''I do play''.', true, CURRENT_DATE),
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', 'Match the modal verb to its primary function.', 'match', '{"left":["May","Can","Must"],"right":["Ability","Strong Obligation","Formal Permission"]}'::jsonb, '{"May":"Formal Permission","Can":"Ability","Must":"Strong Obligation"}', 'Modal Verbs', 'medium', 'This tests the understanding of the different uses for common modal verbs as practiced in the transcript.', true, CURRENT_DATE),
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', 'Match the concept to its correct example.', 'match', '{"left":["Article with Superlative","Passive Voice","Causative Form"],"right":["The shop had already been closed.","I will get the AC repaired.","Is the biggest festival of Christians."]}'::jsonb, '{"Article with Superlative":"Is the biggest festival of Christians.","Passive Voice":"The shop had already been closed.","Causative Form":"I will get the AC repaired."}', 'Grammar Terminology', 'hard', 'This requires identifying specific grammatical structures within sentences that were explicitly taught or corrected.', true, CURRENT_DATE),
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', 'Match the tense with its sentence structure.', 'match', '{"left":["Present Perfect Continuous","Past Perfect","Future Perfect"],"right":["The train had already departed.","I will have reached Dehradun tomorrow.","I have been studying for five hours."]}'::jsonb, '{"Present Perfect Continuous":"I have been studying for five hours.","Past Perfect":"The train had already departed.","Future Perfect":"I will have reached Dehradun tomorrow."}', 'Tense Identification', 'medium', 'This tests the ability to recognize the distinct structures of three different perfect tenses practiced in class.', true, CURRENT_DATE),
  ('98825c00-fb8f-46dc-bec7-3cdd8880efea', 'Match the Hindi question word to its English meaning.', 'match', '{"left":["क्या","कैसे","किसके साथ"],"right":["How","With whom","What"]}'::jsonb, '{"क्या":"What","कैसे":"How","किसके साथ":"With whom"}', 'Interrogative Words', 'easy', 'This tests the basic translation of common question words that were used throughout the practice session.', true, CURRENT_DATE);

-- Step 3: Verify insertion
SELECT COUNT(*) as active_questions
FROM quiz_questions
WHERE student_id = '98825c00-fb8f-46dc-bec7-3cdd8880efea'
  AND active = true;
-- Expected: 30

-- Step 4: Check question type distribution
SELECT
  question_type,
  COUNT(*) as count
FROM quiz_questions
WHERE student_id = '98825c00-fb8f-46dc-bec7-3cdd8880efea'
  AND active = true
GROUP BY question_type
ORDER BY question_type;